name: Vývojářka frontendu
url: /cesta-do-it/vyvojarka-frontendu/
avatar: avatar.jpeg
pathImg: cesta/vyvojarka-frontendu.png
shortDescription: >
  Specializuje se na tvorbu uživatelského rozhraní webových aplikací a je zodpovědná za jejich implementaci. 
  Tato role vyžaduje znalosti moderních frontendových frameworků a schopnost spolupracovat 
  s backendovými vývojáři.
cta: Chci být vývojářka frontendu
aboutRole: >
    Frontend vývojářka vytváří tu část webové stránky, která jde vidět, se kterou pracuješ například, když nakupuješ v e-shopu.
    Třeba když vyplňuješ adresu, platební metodu a stiskneš tlačítko “objednat” - jak vypadá formulář, tlačítko,
    jak dobře se s nimi pracuje atp. To je frontend, co se děje potom, co tlačítko zmáčkneš, to chování za tím,
    to už má na starosti jiný typ vývojářky (backendová vývojářka). To znamená, že frontenďačka potřebuje mj. spolupracovat
    s backendovými vývojáři.
enjoyRole:
    - ráda kreslíš, maluješ, potřebuješ tvořit a potřebuješ, aby tvá práce byla vidět
    - zajímáš se o grafiku, design, estetiku
    - máš ráda, když jsou věci jednoduché a příjemné na používání, všímáš si, jak se věci používají a jestli to nejde udělat lépe a efektivněji
    - zajímá tě i funkční stránka, interakce uživatele, nejen vzhled
    - samozřejmě se zajímáš o technologie a ráda se učíš a hledáš nová řešení
competences:
    - principy vývoje aplikací, komunikace se serverem, zobrazování a zpracování dat, Git
    - HTML/CSS, JavaScript, React
    - základy UX a UI designu
    - angličtina na úrovni čtení dokumentace, pokud se budeš ucházet o práci v mezinárodní firmě nebo se zahraničními zákazníky, počítej s tím, že budeš potřebovat aktivní komunikativní angličtinu
courses:
    intro: 'DAT-10.' 
    core: 'DAT-(.2.)'