name: Bezpečnostní specialistka
url: /cesta-do-it/bezpecnostni-specialistka/
avatar: avatar.jpeg
pathImg: cesta/bezpecnostni-specialistka.png
shortDescription: >
    Specializuje se na implementaci a správu bezpečnostních opatření a technologií v organizaci. Je zodpovědná za identifikaci
    a řešení bezpečnostních hrozeb a provádění preventivních opatření.
cta: Chci být bezp. specialistka
aboutRole: > 
    Naše data nejsou jen informace, jsou to zdroje, mají hodnotu, je tedy možné je i ukrást nebo zneužít, a to jak u jednotlivců,
    tak u firem. Bezpečnostní specialistka se zaměřuje na nasazení a správu bezpečnostních opatření a technologií v organizaci
    (například firewall, antivirový software, šifrování a autentizace). Jejím hlavním úkolem je zajistit, že IT systémy a sítě
    jsou chráněny před různými hrozbami a že jsou v souladu s bezpečnostními standardy a předpisy. Na rozdíl od SOC analytičky
    se tedy zaměřuje více na oblast samotného zabezpečení IT infrastruktury a implementaci bezpečnostních opatření.
enjoyRole:
    - máš ráda hádanky, logické hry
    - zajímáš se o svou bezpečnost na internetu a svých dat
    - raději problémům předcházíš, dokážeš udržet klid a soustředění v stresových situacích
    - máš dobré pozorovací a komunikační schopnosti, hledáš neotřelá řešení na problém, který je před tebou
    - samozřejmě se zajímáš o technologie a ráda se učíš
competences:
    - operační systémy, sítě
    - legislativa
    - skenování zranitelnosti, penetrační testy, šifrovací metody, bezpečnostní politiky, postupy a reakce na bezpečnostní incidenty
    - nástroje pro analýzu incidentů a síťového provozu
    - aktivní komunikativní angličtinu
courses:
    intro: 'CS-101' 
    core: 'CS-.11'